### ISSUE TITLE
🚧Add workflow to auto label new issues

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#10]
**Description:**
Create a workflow file that auto adds a triage label to newly created issues.

Refer to [GitHub docs](https://docs.github.com/en/actions/guides/adding-labels-to-issues) for more info
Refer to [Action docs](https://github.com/marketplace/actions/simple-issue-labeler)

---

**Acceptance Criteria:**

1. [ ] Workflow created
2. [ ] Workflow running successfully

**Comment by teezzan** [comment]
Hello, Can I hop on this?

**Comment by CalvinWilkinson** [comment]
> Hello, Can I hop on this? 

Absolutely!!  Thanks for the help!!

**Comment by teezzan** [comment]
I am going to be doing a lot of DevOp-sy contributions and I don't know a lot yet. Please, bear with me.

**Comment by CalvinWilkinson** [comment]
not a problem.  I am very experienced in DevOps kind of stuff as well as CI/CD pipelines due to my experience in the enterprise space.  If you need any help or have questions, let me know. :)

**Comment by teezzan** [comment]
I branched from the `develop` branch. Is that okay?

**Comment by teezzan** [comment]
## Status
- [x]  Workflow created
- [ ] Workflow running successfully
