### ISSUE TITLE
🚧 Search and replace all equality checks with pattern matching

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#101]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Search through code base for all `==` and `!=` checks with reference types and replace them with `is null` and `is not null`.

This is for a bit of a performance boost but most of all it is for avoiding incorrect checks that can occur if the `==` or `!=` operators are overloaded.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed

**Comment by ljdarj** [comment]
I wish to take up this issue if it's still current.
