### ISSUE TITLE
🚧Normalize code docs for IGlnvoker and IGLInvokerExtension for ctor injection

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#106]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

Search and find all code docs for constructor injection of the `IGLInvoker` and `IGLInvokerExtensions` types and make sure that the documentation for all of them match.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed

**Comment by CalvinWilkinson** [comment]
A new issue #122 will take on this work.
