### ISSUE TITLE
🚧Improve perf of uploading GPU vertex data

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#107]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Description

In the `GPUBufferBase` class, refactor the `UploadVertexData()` method `TData` param to be an IN parameter as well as the generic parameter if required.  

Before refactoring this, collect some performance data and also measure performance after to verify that performance is being improved.  If not implemented properly, performance can be worse.

Refer to [this video](https://www.youtube.com/watch?v=VCGXubxKL9I) for explanation:

### Acceptance Criteria

**This issue is finished when:**
- [ ] Code documentation added if required
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [ ] Draft pull request created and linked to this issue
- [X] Priority label added to issue (**_low priority_**, **_medium priority_**, or **_high priority_**)
- [X] Issue linked to the proper project
- [X] Issue linked to proper milestone
- [ ] Unit tests have been written and/or adjusted for code additions or changes
- [ ] All unit tests pass

**Comment by kselena** [comment]
Groomed
