### ISSUE TITLE
🐛Button mouse up behavior not working correctly

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/Velaptor#110]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the mouse is in the down position, and then while in the down position the mouse is moved off of the face of the button before letting go of the mouse button, the MouseUp event is not triggered. 

Change the behavior of the MouseUp event by having it triggered when the mouse button is released AND the mouse is NOT over the button.

### Expected Behavior

When the mouse button is released and NOT over the face of a button/control, the `MouseUp` event is still triggered.

### Steps To Reproduce

1. Run the **Velaptor Testing Application**
2. Goto the **Text Rendering Scene** which has buttons to control attributes of the text being rendered
3. Click down on the CW button and hold the mouse button down.
4. While keep the mouse button in the down position, move the mouse off of the face of the button
5. Let go of the mouse button

### Operating System

- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] Mac OS
- [ ] iOS

### If you now what OS version the bug occurred on, enter the OS version here

Windows 11 - 21H2 (OS Build 22000.376)

**Comment by kselena** [comment]
Reviewed with @CalvinWilkinson

**Comment by CalvinWilkinson** [comment]
After investigation into the issue, the behavior of the `Button` control itself is working as intended.  This is a result of how the `MouseUp` and `MouseDown` events are being utilized in the testing application scene.  Basically, this is not a bug.  😃

When the UI controls are changed for a slider control for issue #186 .

This will be implemented using issue #207
