### ISSUE TITLE
✨Add descriptive text to animated graphic scene

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#115]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Is there an existing feature request that has already been created?

- [X] I have searched the exiting features

### Is your feature request related to a problem? Please describe.

As a QA tester, I wasn't sure what the animated graphic scene was supposed to do.

### Describe the solution you would like?

Add descriptive text to explain what is expected for that animated graphic scene.

### Alternative Solutions

Let me know specifically the functionality that the scene is supposed to have, if it is supposed to change rotation and/or color. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Closed without implementation

**Reason:** Does not apply anymore
