### ISSUE TITLE
✨Create slider UI control 

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#186]
## I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

## Is there an existing feature request that has already been created?

- [X] I have searched the exiting features

## Is your feature request related to a problem? Please describe.

Need a control to make it easier to test out various things in the **Velaptor Testing Application**.  This control could not only be used by users but also to quickly and easily change various attributes of items being tested in the testing application.

Example: This could be used to change various attributes of the rectangle in the **VelaptorTesting** application

### Create a **Slider Control** simular to the image below:
![image](https://user-images.githubusercontent.com/85414302/154818046-9c21c412-21c0-4422-ad4c-88cdb9f623a2.png)

This will be a composite control containing the following controls:
1. Label control for min value
2. Label control for max value
3. Label control for current value
4. ShapeButton for horizontal bar to the left of the drag button
5. ShapeButton for horizontal bar to the right of the drag button
6. ShapeButton for drag button

###  Labels:
  - [ ] Has a Min and Max value in standard units.
    - NOTE: This unit of measurement is not in pixel units.  It is just a number.
  - [ ] Visibility property to show or hide the min value label
  - [ ] Visibility property to show or hide the max value label
  - [ ] Visibility property to show or hide the current value label
  - [ ] Able to show the current value either centered above or below the drag button
    - This value will have to be calculated based on the physical left and right of the control relative to the position of the center of the drag button on its X axis.
  - [ ] Ability to choose if the current value label is above or below the drag button via a **property** with an enum type.
### Drag Button:
  - [ ] The drag button should be displayed as a solid color with no border
  - [ ] Able to control corner radius of drag button
  - [ ] Able to change the drag button color
  - Dragging Button Behavior:
    - [ ] Able to grab the drag button with the mouse and drag left to right.
    - [ ] ShapeButton will follow the mouse on the X axis as long as the mouse button is in the down position and ONLY moves on the X axis.
    - [ ] Updates the current value
    - [ ] Drag button center X cannot move farther left than the left end of the horizontal bar
    - [ ] Drag button center X cannot move farther right than the right end of horizontal bar
  - [ ] Reducing the height of the drag button will have a min value that is <= 25% larger than the horizontal bar height
  - [ ] The horizontal center of the drag button is the reference point between the button and the left or right end of the horizontal bar.
    - NOTE: If the button is all the way to the min value, the CENTER of the button is what would horizontally line up with the left end of the horizontal bar.  The same goes for the right end of the horizontal bar.
### Horizontal Bar:
  - NOTE: The bar is made up of 2 Buttons. One button for the left side of the drag button and one for the right side.
  - [ ] Able to control corner radius of horizontal bar
  - [ ] Able to control the thickness of the horizontal bar
    - [ ] Limit the thickness of the horizontal bar to a max that is 75% of the drag button height.  This is to prevent the horizontal bar from being thicker which would make the control not look like a slider control anymore.
  - [ ] The horizontal bar section to the left of the drag button will be a customizable color via a **property**
  - [ ] The horizontal bar section to the right of the drag button will be a customizable color via a **property**
  - [ ] Increasing the horizontal bar height will have a max value that is <= 75% of the drag button height
  - [ ] Property added to set the decrement value when the mouse is clicked to the left of the drag button
  - [ ] Property added to set the increment value when the mouse is clicked to the right of the drag button
  - [ ] Clicking the mouse to the left of the drag button will decrement the current value
      - The mouse must be to the left of the drag button left edge and to the right of the left end of the horizontal bar
      - [ ] Updates the current value
  - [ ] Clicking the mouse to the right of the drag button will increment the current value
      - The mouse must be to the right of the drag button right edge and to the left of the right end of the horizontal bar
      - [ ] Updates the current value
### Disabling entire control:
  - Labels will automatically be updated to reflect same enabled state as slider control
  - Disabled color for disabled drag button
  - Disabled color for disabled horizontal bar
**Example of control below:**

## Alternative Solutions

None.  This control does not exist yet. The request is to simply create the currently non-existent control

## Dependencies
- #213 

## Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CalvinWilkinson** [comment]
Issue taken out of the _**v1.0.0-preview.8**_ release.  The issue requires too many changes as well as a dependency on #213 to be completed.
