### ISSUE TITLE
🐛Unwanted text showing in test keyboard scene

### ISSUE THREAD

**Issue by kselena** [KinsonDigital/Velaptor#223]
### I have done the items below . . .

- [X] I have updated the title by replacing the '**_<title_**>' section.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The word "unknown" stays on the screen while clicking all keyboard keys.

https://user-images.githubusercontent.com/96791049/156934477-953678dd-2c21-4c7a-abea-cd0c274975d6.mp4

### Expected Behavior

The word "unknown" should not appear in the test keyboard scene.

### Steps To Reproduce

1. In Velaptor test keyboard scene 
2. Click any button on the keyboard
3. Observe result

### Operating System

- [X] Windows
- [ ] Linux
- [ ] Android
- [ ] Mac OS
- [ ] iOS

### If you now what OS version the bug occurred on, enter the OS version here

![image](https://user-images.githubusercontent.com/96791049/156934724-a18fd218-5b0b-46ac-bdad-3ed48b5b6863.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kselena** [comment]
Did additional testing and we couldn't reproduce the issue.

**Comment by CalvinWilkinson** [comment]
Previous attempts have been made to reproduce this issue and the issue could not be reproduced.

It also has not been seen since.  The assumption is that somehow the casting of the keyboard key was defaulted to the text unknown due to the keyboard key value being a value that does not exist in the enum
